language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
    - pip install -U pytest pytest-pep8 pytest-cov coveralls
    - python setup.py --verbose install
script:
    - python setup.py --verbose test
after_success:
  - coveralls
