language: python

python:
    - "3.3"
    - "3.4"
    - "3.5"

install:
    - pip install -U pytest pytest-pep8 pytest-cov coveralls
    - pip install -e .

script:
    - py.test --cov http_filter --pep8

after_success:
    - coveralls
