language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
    - pip install -U pytest pytest-pep8 pytest-cov python-coveralls
    - python setup.py install
script:
    - python setup.py test
    - cat .coverage 
after_success:
  - coveralls
