language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
    - pip install -U -q pytest pytest-pep8 python-coveralls
script:
    - PYTHONPATH="./src" py.test --pep8 --cov src
after_success:
  - coveralls
